openapi: "3.0.2"
info:
  title: book manager API
  description: ""
  version: "1.0"
servers:
  - url: http://localhost:8080/api/v1
    description: book manager API
    variables:
      api_version:
        default: "v1"
        enum:
          - "v1"
paths:
  /admin/book/register:
    post:
      tags:
        - AdminBook
      summary: "書籍の登録"
      operationId: adminBookRegister
      description: ""
      deprecated: false
      requestBody:
        description: ""
        required: true
        content:
          application/json:
            schema:
              $ref: ./components/schema/model/book.yaml
      responses:
        '200':
          description: 書籍の登録成功
          content:
            application/json:
              schema:
                type: object
                properties: {}
  /admin/book/update:
    put:
      tags:
        - AdminBook
      summary: "書籍の更新"
      operationId: update
      description: ""
      deprecated: false
      requestBody:
        description: ""
        required: true
        content:
          application/json:
            schema:
              $ref: ./components/schema/model/book.yaml
      responses:
        '200':
          description: 書籍の更新成功
          content:
            application/json:
              schema:
                type: object
                properties: {}
        '500':
          description: 書籍の更新失敗
          content:
            application/json:
              schema:
                type: object
                properties: {}
  /admin/book/delete:
    delete:
      tags:
        - AdminBook
      summary: "書籍の削除"
      operationId: delete
      description: ""
      deprecated: false
      requestBody:
        description: ""
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                  description: 書籍ID
      responses:
        '200':
          description: 書籍の削除成功
          content:
            application/json:
              schema:
                type: object
                properties: {}
        '500':
          description: 書籍の削除失敗
          content:
            application/json:
              schema:
                type: object
                properties: {}


components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Application-Authorization

security:
  - ApiKeyAuth: [client]